//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CVsModel", "FK_Education_CV", "CVs", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UploadXmlCvsToSite.CV), "Education", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UploadXmlCvsToSite.Education), true)]
[assembly: EdmRelationshipAttribute("CVsModel", "FK_Skills_CV", "CVs", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UploadXmlCvsToSite.CV), "Skills", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UploadXmlCvsToSite.Skill), true)]
[assembly: EdmRelationshipAttribute("CVsModel", "FK_WorkExperiance_CV", "CVs", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UploadXmlCvsToSite.CV), "WorkExperiance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UploadXmlCvsToSite.WorkExperiance), true)]
[assembly: EdmRelationshipAttribute("CVsModel", "FK_Subjects_Education", "Education", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UploadXmlCvsToSite.Education), "Subjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UploadXmlCvsToSite.Subject), true)]
[assembly: EdmRelationshipAttribute("CVsModel", "FK_CVs_User", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UploadXmlCvsToSite.User), "CVs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UploadXmlCvsToSite.CV), true)]

#endregion

namespace UploadXmlCvsToSite
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CVsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CVsEntities object using the connection string found in the 'CVsEntities' section of the application configuration file.
        /// </summary>
        public CVsEntities() : base("name=CVsEntities", "CVsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CVsEntities object.
        /// </summary>
        public CVsEntities(string connectionString) : base(connectionString, "CVsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CVsEntities object.
        /// </summary>
        public CVsEntities(EntityConnection connection) : base(connection, "CVsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CV> CVSet
        {
            get
            {
                if ((_CVSet == null))
                {
                    _CVSet = base.CreateObjectSet<CV>("CVSet");
                }
                return _CVSet;
            }
        }
        private ObjectSet<CV> _CVSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Education> EducationSet
        {
            get
            {
                if ((_EducationSet == null))
                {
                    _EducationSet = base.CreateObjectSet<Education>("EducationSet");
                }
                return _EducationSet;
            }
        }
        private ObjectSet<Education> _EducationSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Skill> SkillSet
        {
            get
            {
                if ((_SkillSet == null))
                {
                    _SkillSet = base.CreateObjectSet<Skill>("SkillSet");
                }
                return _SkillSet;
            }
        }
        private ObjectSet<Skill> _SkillSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subject> SubjectSet
        {
            get
            {
                if ((_SubjectSet == null))
                {
                    _SubjectSet = base.CreateObjectSet<Subject>("SubjectSet");
                }
                return _SubjectSet;
            }
        }
        private ObjectSet<Subject> _SubjectSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> UserSet
        {
            get
            {
                if ((_UserSet == null))
                {
                    _UserSet = base.CreateObjectSet<User>("UserSet");
                }
                return _UserSet;
            }
        }
        private ObjectSet<User> _UserSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkExperiance> WorkExperianceSet
        {
            get
            {
                if ((_WorkExperianceSet == null))
                {
                    _WorkExperianceSet = base.CreateObjectSet<WorkExperiance>("WorkExperianceSet");
                }
                return _WorkExperianceSet;
            }
        }
        private ObjectSet<WorkExperiance> _WorkExperianceSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CVSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCVSet(CV cV)
        {
            base.AddObject("CVSet", cV);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EducationSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEducationSet(Education education)
        {
            base.AddObject("EducationSet", education);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SkillSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSkillSet(Skill skill)
        {
            base.AddObject("SkillSet", skill);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SubjectSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubjectSet(Subject subject)
        {
            base.AddObject("SubjectSet", subject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkExperianceSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkExperianceSet(WorkExperiance workExperiance)
        {
            base.AddObject("WorkExperianceSet", workExperiance);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CVsModel", Name="CV")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CV : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CV object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="born">Initial value of the born property.</param>
        /// <param name="nationality">Initial value of the nationality property.</param>
        /// <param name="liveIncity">Initial value of the liveIncity property.</param>
        /// <param name="dateAdded">Initial value of the dateAdded property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="gender">Initial value of the gender property.</param>
        public static CV CreateCV(global::System.Int64 id, global::System.Int64 userID, global::System.Int32 born, global::System.String nationality, global::System.String liveIncity, global::System.DateTime dateAdded, global::System.String description, global::System.String gender)
        {
            CV cV = new CV();
            cV.ID = id;
            cV.UserID = userID;
            cV.born = born;
            cV.nationality = nationality;
            cV.liveIncity = liveIncity;
            cV.dateAdded = dateAdded;
            cV.description = description;
            cV.gender = gender;
            return cV;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int64 _UserID;
        partial void OnUserIDChanging(global::System.Int64 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 born
        {
            get
            {
                return _born;
            }
            set
            {
                OnbornChanging(value);
                ReportPropertyChanging("born");
                _born = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("born");
                OnbornChanged();
            }
        }
        private global::System.Int32 _born;
        partial void OnbornChanging(global::System.Int32 value);
        partial void OnbornChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nationality
        {
            get
            {
                return _nationality;
            }
            set
            {
                OnnationalityChanging(value);
                ReportPropertyChanging("nationality");
                _nationality = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nationality");
                OnnationalityChanged();
            }
        }
        private global::System.String _nationality;
        partial void OnnationalityChanging(global::System.String value);
        partial void OnnationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String liveIncity
        {
            get
            {
                return _liveIncity;
            }
            set
            {
                OnliveIncityChanging(value);
                ReportPropertyChanging("liveIncity");
                _liveIncity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("liveIncity");
                OnliveIncityChanged();
            }
        }
        private global::System.String _liveIncity;
        partial void OnliveIncityChanging(global::System.String value);
        partial void OnliveIncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String details
        {
            get
            {
                return _details;
            }
            set
            {
                OndetailsChanging(value);
                ReportPropertyChanging("details");
                _details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("details");
                OndetailsChanged();
            }
        }
        private global::System.String _details;
        partial void OndetailsChanging(global::System.String value);
        partial void OndetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateAdded
        {
            get
            {
                return _dateAdded;
            }
            set
            {
                OndateAddedChanging(value);
                ReportPropertyChanging("dateAdded");
                _dateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateAdded");
                OndateAddedChanged();
            }
        }
        private global::System.DateTime _dateAdded;
        partial void OndateAddedChanging(global::System.DateTime value);
        partial void OndateAddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_Education_CV", "Education")]
        public EntityCollection<Education> Education
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Education>("CVsModel.FK_Education_CV", "Education");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Education>("CVsModel.FK_Education_CV", "Education", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_Skills_CV", "Skills")]
        public EntityCollection<Skill> Skills
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Skill>("CVsModel.FK_Skills_CV", "Skills");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Skill>("CVsModel.FK_Skills_CV", "Skills", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_WorkExperiance_CV", "WorkExperiance")]
        public EntityCollection<WorkExperiance> WorkExperiance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WorkExperiance>("CVsModel.FK_WorkExperiance_CV", "WorkExperiance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WorkExperiance>("CVsModel.FK_WorkExperiance_CV", "WorkExperiance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_CVs_User", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("CVsModel.FK_CVs_User", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("CVsModel.FK_CVs_User", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("CVsModel.FK_CVs_User", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("CVsModel.FK_CVs_User", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CVsModel", Name="Education")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Education : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Education object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cvID">Initial value of the CvID property.</param>
        /// <param name="fromDate">Initial value of the fromDate property.</param>
        /// <param name="placeName">Initial value of the placeName property.</param>
        /// <param name="location">Initial value of the location property.</param>
        public static Education CreateEducation(global::System.Int64 id, global::System.Int64 cvID, global::System.DateTime fromDate, global::System.String placeName, global::System.String location)
        {
            Education education = new Education();
            education.ID = id;
            education.CvID = cvID;
            education.fromDate = fromDate;
            education.placeName = placeName;
            education.location = location;
            return education;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CvID
        {
            get
            {
                return _CvID;
            }
            set
            {
                OnCvIDChanging(value);
                ReportPropertyChanging("CvID");
                _CvID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CvID");
                OnCvIDChanged();
            }
        }
        private global::System.Int64 _CvID;
        partial void OnCvIDChanging(global::System.Int64 value);
        partial void OnCvIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fromDate
        {
            get
            {
                return _fromDate;
            }
            set
            {
                OnfromDateChanging(value);
                ReportPropertyChanging("fromDate");
                _fromDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fromDate");
                OnfromDateChanged();
            }
        }
        private global::System.DateTime _fromDate;
        partial void OnfromDateChanging(global::System.DateTime value);
        partial void OnfromDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> toDate
        {
            get
            {
                return _toDate;
            }
            set
            {
                OntoDateChanging(value);
                ReportPropertyChanging("toDate");
                _toDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("toDate");
                OntoDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _toDate;
        partial void OntoDateChanging(Nullable<global::System.DateTime> value);
        partial void OntoDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String placeName
        {
            get
            {
                return _placeName;
            }
            set
            {
                OnplaceNameChanging(value);
                ReportPropertyChanging("placeName");
                _placeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("placeName");
                OnplaceNameChanged();
            }
        }
        private global::System.String _placeName;
        partial void OnplaceNameChanging(global::System.String value);
        partial void OnplaceNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String details
        {
            get
            {
                return _details;
            }
            set
            {
                OndetailsChanging(value);
                ReportPropertyChanging("details");
                _details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("details");
                OndetailsChanged();
            }
        }
        private global::System.String _details;
        partial void OndetailsChanging(global::System.String value);
        partial void OndetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String level
        {
            get
            {
                return _level;
            }
            set
            {
                OnlevelChanging(value);
                ReportPropertyChanging("level");
                _level = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("level");
                OnlevelChanged();
            }
        }
        private global::System.String _level;
        partial void OnlevelChanging(global::System.String value);
        partial void OnlevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major
        {
            get
            {
                return _major;
            }
            set
            {
                OnmajorChanging(value);
                ReportPropertyChanging("major");
                _major = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("major");
                OnmajorChanged();
            }
        }
        private global::System.String _major;
        partial void OnmajorChanging(global::System.String value);
        partial void OnmajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_Education_CV", "CVs")]
        public CV CV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_Education_CV", "CVs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_Education_CV", "CVs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CV> CVReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_Education_CV", "CVs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CV>("CVsModel.FK_Education_CV", "CVs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_Subjects_Education", "Subjects")]
        public EntityCollection<Subject> Subjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Subject>("CVsModel.FK_Subjects_Education", "Subjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Subject>("CVsModel.FK_Subjects_Education", "Subjects", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CVsModel", Name="Skill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Skill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Skill object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="skill1">Initial value of the skill property.</param>
        /// <param name="cvID">Initial value of the CvID property.</param>
        public static Skill CreateSkill(global::System.Int64 id, global::System.String skill1, global::System.Int64 cvID)
        {
            Skill skill = new Skill();
            skill.ID = id;
            skill.skill = skill1;
            skill.CvID = cvID;
            return skill;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String skill
        {
            get
            {
                return _skill;
            }
            set
            {
                OnskillChanging(value);
                ReportPropertyChanging("skill");
                _skill = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("skill");
                OnskillChanged();
            }
        }
        private global::System.String _skill;
        partial void OnskillChanging(global::System.String value);
        partial void OnskillChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gradation
        {
            get
            {
                return _gradation;
            }
            set
            {
                OngradationChanging(value);
                ReportPropertyChanging("gradation");
                _gradation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gradation");
                OngradationChanged();
            }
        }
        private global::System.String _gradation;
        partial void OngradationChanging(global::System.String value);
        partial void OngradationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String details
        {
            get
            {
                return _details;
            }
            set
            {
                OndetailsChanging(value);
                ReportPropertyChanging("details");
                _details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("details");
                OndetailsChanged();
            }
        }
        private global::System.String _details;
        partial void OndetailsChanging(global::System.String value);
        partial void OndetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CvID
        {
            get
            {
                return _CvID;
            }
            set
            {
                OnCvIDChanging(value);
                ReportPropertyChanging("CvID");
                _CvID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CvID");
                OnCvIDChanged();
            }
        }
        private global::System.Int64 _CvID;
        partial void OnCvIDChanging(global::System.Int64 value);
        partial void OnCvIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_Skills_CV", "CVs")]
        public CV CV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_Skills_CV", "CVs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_Skills_CV", "CVs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CV> CVReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_Skills_CV", "CVs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CV>("CVsModel.FK_Skills_CV", "CVs", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CVsModel", Name="Subject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subject object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="eduID">Initial value of the EduID property.</param>
        /// <param name="subject1">Initial value of the subject property.</param>
        public static Subject CreateSubject(global::System.Int64 id, global::System.Int64 eduID, global::System.String subject1)
        {
            Subject subject = new Subject();
            subject.ID = id;
            subject.EduID = eduID;
            subject.subject = subject1;
            return subject;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EduID
        {
            get
            {
                return _EduID;
            }
            set
            {
                OnEduIDChanging(value);
                ReportPropertyChanging("EduID");
                _EduID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EduID");
                OnEduIDChanged();
            }
        }
        private global::System.Int64 _EduID;
        partial void OnEduIDChanging(global::System.Int64 value);
        partial void OnEduIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String subject
        {
            get
            {
                return _subject;
            }
            set
            {
                OnsubjectChanging(value);
                ReportPropertyChanging("subject");
                _subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("subject");
                OnsubjectChanged();
            }
        }
        private global::System.String _subject;
        partial void OnsubjectChanging(global::System.String value);
        partial void OnsubjectChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_Subjects_Education", "Education")]
        public Education Education
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Education>("CVsModel.FK_Subjects_Education", "Education").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Education>("CVsModel.FK_Subjects_Education", "Education").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Education> EducationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Education>("CVsModel.FK_Subjects_Education", "Education");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Education>("CVsModel.FK_Subjects_Education", "Education", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CVsModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="email">Initial value of the email property.</param>
        public static User CreateUser(global::System.Int64 id, global::System.String firstName, global::System.String lastName, global::System.String email)
        {
            User user = new User();
            user.ID = id;
            user.firstName = firstName;
            user.lastName = lastName;
            user.email = email;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_CVs_User", "CVs")]
        public EntityCollection<CV> CVs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CV>("CVsModel.FK_CVs_User", "CVs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CV>("CVsModel.FK_CVs_User", "CVs", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CVsModel", Name="WorkExperiance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkExperiance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkExperiance object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cvID">Initial value of the CvID property.</param>
        /// <param name="fromDate">Initial value of the fromDate property.</param>
        /// <param name="position">Initial value of the position property.</param>
        public static WorkExperiance CreateWorkExperiance(global::System.Int64 id, global::System.Int64 cvID, global::System.DateTime fromDate, global::System.String position)
        {
            WorkExperiance workExperiance = new WorkExperiance();
            workExperiance.ID = id;
            workExperiance.CvID = cvID;
            workExperiance.fromDate = fromDate;
            workExperiance.position = position;
            return workExperiance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CvID
        {
            get
            {
                return _CvID;
            }
            set
            {
                OnCvIDChanging(value);
                ReportPropertyChanging("CvID");
                _CvID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CvID");
                OnCvIDChanged();
            }
        }
        private global::System.Int64 _CvID;
        partial void OnCvIDChanging(global::System.Int64 value);
        partial void OnCvIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fromDate
        {
            get
            {
                return _fromDate;
            }
            set
            {
                OnfromDateChanging(value);
                ReportPropertyChanging("fromDate");
                _fromDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fromDate");
                OnfromDateChanged();
            }
        }
        private global::System.DateTime _fromDate;
        partial void OnfromDateChanging(global::System.DateTime value);
        partial void OnfromDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> toDate
        {
            get
            {
                return _toDate;
            }
            set
            {
                OntoDateChanging(value);
                ReportPropertyChanging("toDate");
                _toDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("toDate");
                OntoDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _toDate;
        partial void OntoDateChanging(Nullable<global::System.DateTime> value);
        partial void OntoDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String companyName
        {
            get
            {
                return _companyName;
            }
            set
            {
                OncompanyNameChanging(value);
                ReportPropertyChanging("companyName");
                _companyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("companyName");
                OncompanyNameChanged();
            }
        }
        private global::System.String _companyName;
        partial void OncompanyNameChanging(global::System.String value);
        partial void OncompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String position
        {
            get
            {
                return _position;
            }
            set
            {
                OnpositionChanging(value);
                ReportPropertyChanging("position");
                _position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("position");
                OnpositionChanged();
            }
        }
        private global::System.String _position;
        partial void OnpositionChanging(global::System.String value);
        partial void OnpositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String details
        {
            get
            {
                return _details;
            }
            set
            {
                OndetailsChanging(value);
                ReportPropertyChanging("details");
                _details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("details");
                OndetailsChanged();
            }
        }
        private global::System.String _details;
        partial void OndetailsChanging(global::System.String value);
        partial void OndetailsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CVsModel", "FK_WorkExperiance_CV", "CVs")]
        public CV CV
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_WorkExperiance_CV", "CVs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_WorkExperiance_CV", "CVs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CV> CVReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CV>("CVsModel.FK_WorkExperiance_CV", "CVs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CV>("CVsModel.FK_WorkExperiance_CV", "CVs", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
